### ISSUE TITLE
esd_text.txt

### ISSUE THREAD

**Issue by jihoojung0106** [Choddeok/EmoSphere-TTS#1]
how can i get esd_text.txt?

**Comment by Choddeok** [comment]
Thank you for your interest in my paper.

I have updated the requested section in the esd_text.txt file (**esd_text_emo.txt**).

You should be able to run the process without any issues by changing the path to the required txt file (**esd_text_emo.txt**) and adding it to the **self.raw_data_dir** directory. 

For more detailed information on the preprocessing steps, you may find it helpful to refer to the repository at https://github.com/NATSpeech/NATSpeech.

Thank you.

**Comment by jihoojung0106** [comment]
Thank you for your kind answer. One more question. 
`tasks/tts/dataset_utils.py` line 65 `emo_VAD_polar = torch.Tensor(item['emo_VAD_polar'])`. but item doesn't have key named "emo_VAD_polar".  I guess it should be`emo_VAD_polar = torch.Tensor(item['spherical_emotion_vector'])`?

**Comment by Choddeok** [comment]
Yes, that's correct. The term `emo_VAD_polar` should be changed to `spherical_emotion_vector`.

I will update the relevant section accordingly.

Thank you for bringing this issue to my attention.

**Comment by zdj97** [comment]
Hi could you help me run this repo?
I can not run this repo.
Thanks
